export const FETCH_MOVIE_FAIL = 'FETCH_MOVIE_FAIL';
export const FETCH_MOVIE_PENDING = 'FETCH_MOVIE_PENDING';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_SELECTED_MOVIE_FAIL = 'FETCH_SELECTED_MOVIE_FAIL';
export const FETCH_SELECTED_MOVIE_PENDING = 'FETCH_SELECTED_MOVIE_PENDING';
export const FETCH_SELECTED_MOVIE_SUCCESS = 'FETCH_SELECTED_MOVIE_SUCCESS';
export const CLEAR_MOVIE_DETAILS = 'CLEAR_MOVIE_DETAILS';